In [1]:
#np.random的统计函数(1)
    #sum(a,axis=None):根据给定轴axis计算数组a相关元素之和，axis整数或元组
    #mean(a,axis=None):根据给定轴axis计算数组a相关元素的期望，axis整数或元组
    #average(a,axis=None,weights=None):根据给定轴axis计算数组a相关元素的加权平均值
    #std(a,axis=None):根据给定轴axis计算数组a相关元素的标准差
    #var(a,axis=None):根据给定轴axis计算数组a相关元素的方差

In [2]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
np.sum(a)

105

In [5]:
np.mean(a,axis=1)

array([  2.,   7.,  12.])

In [6]:
np.mean(a,axis=0)

array([ 5.,  6.,  7.,  8.,  9.])

In [8]:
np.average(a,axis=0,weights=[10,5,1])  #4.1875=(2*10+7*5+12*1)/(10+5+1)

array([ 2.1875,  3.1875,  4.1875,  5.1875,  6.1875])

In [9]:
np.std(a)

4.3204937989385739

In [10]:
np.var(a)

18.666666666666668

In [11]:
#np.random的统计函数(2)
    #min(a) max(a):计算数组a中元素的最小值、最大值
    #argmin(a) argmax(a):计算数组a中元素最小值、最大值的降一维后下标
    #unravel_index(index,shape):根据shape将一维下标index转换成多维下标
    #ptp(a):计算数组a中元素最大值与最小值的差
    #median(a):计算数组a中元素的中位数(中值)

In [12]:
b = np.arange(15,0,-1).reshape(3,5)
b

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [13]:
np.max(b)

15

In [14]:
np.argmax(b)

0

In [15]:
np.unravel_index(np.argmax(b),b.shape)

(0, 0)

In [16]:
np.ptp(b)

14

In [17]:
np.median(b)

8.0