In [ ]:
#ndarray数组的操作
    #索引：获取数组中特定位置元素的过程
    #切片：获取数组元素子集的过程

In [2]:
import numpy as np
#一维数组的索引和切片：与Python列表类似
a = np.array([9,8,7,6,5])
a[2] 

7

In [3]:
a[1:4:2]  #起始编号：终止编号(不含)：步长

array([8, 6])

In [4]:
#多维数组的索引和切片
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
a[1,2,3]

23

In [6]:
a[0,1,2]

6

In [7]:
a[-1,-2,-3]

17

In [8]:
a[:,1,-3]  #选取一个维度用

array([ 5, 17])

In [9]:
a[:,1:3,:]  #每个维度切片方法与一维数组相同

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
a[:,:,::2]  #每个维度可以使用步长跳跃切片

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])