In [2]:
#ndarray数组的创建方法

In [8]:
import numpy as np
#(1)从Python中的列表、元组等类型创建ndarray数组：x=np.array(list/tuple,dtype=np.float32) 不指定dtype时，NumPy将根据数据情况关联一个dtype类型
x = np.array([0,1,2,3])
print(x)

[0 1 2 3]


In [9]:
x = np.array((4,5,6,7))
print(x)

[4 5 6 7]


In [10]:
x = np.array([[1,2],[9,8],(0.1,0.2)])
print(x)

[[ 1.   2. ]
 [ 9.   8. ]
 [ 0.1  0.2]]


In [12]:
#(2)使用NumPy中函数创建ndarray，如：arange，ones，zeros等
    #np.arange(n):类似range()函数，返回ndarray类型，元素从0到n-1
    #np.ones(shape):根据shape生成一个全1数组，shape是元组类型
    #np.zeros(shape):根据shape生成一个全0数组，shape是元组类型
    #np.full(shape,val):根据shape生成一个数组，每个元素值都是val
    #np.eye(n):创建一个正方的n*n单位矩阵，对角线为1，其余为0
    #np.ones_like(a):根据数组a的形状生成一个全1数组
    #np.zeros_like(a):根据数组a的形状生成一个全0数组
    #np.full_like(a,val):根据数组a的形状生成一个数组，每个元素值都是val

In [13]:
np.arange(10)  #dtype是整型

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.ones((3,6))  #np.ones/np.zeros/np/eye：生成的数组元素的类型是浮点数类型，除非你指定dtype

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [15]:
np.zeros((3,6),dtype=np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [16]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [17]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [18]:
#(3)使用NumPy中其他函数创建ndarray数组
    #np.linspace():根据起止数据等间距地填充数据，形成数组
    #np.concatenate():将两个或多个数组合并成一个新的数组

In [20]:
a = np.linspace(1,10,4)
a

array([  1.,   4.,   7.,  10.])

In [21]:
b = np.linspace(1,10,4,endpoint=False)
b

array([ 1.  ,  3.25,  5.5 ,  7.75])

In [26]:
c = np.concatenate((a,b))
c

array([  1.  ,   4.  ,   7.  ,  10.  ,   1.  ,   3.25,   5.5 ,   7.75])

In [27]:
#ndarray数组的维度变换
    #.reshape(shape):不改变数组元素，返回一个shape形状的数组，原数组不变
    #.resize(shape):与.reshape()功能一致，但修改原数组
    #.swapaxes(ax1,ax2):将数组n个维度中两个维度进行调换
    #.flatten():对数组进行降维，返回折叠后的一维数组，原数组不变

In [30]:
a = np.ones((2,3,4),dtype=np.int32)
a.reshape((3,8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [31]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [34]:
a.resize((3,8))

In [35]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [36]:
a.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1], dtype=int32)

In [37]:
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [38]:
#ndarray数组的类型变换
    #new_a = a.astype(new_type)  astype()方法一定会创建新的数组(原始数据的一个拷贝)，即使两个类型一致。
a = np.ones((2,3,4),dtype=np.int) #np.int:表示整数类，具体解析为int8/int32/int64由程序自动调节
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [39]:
b = a.astype(np.float)
b

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [41]:
#ndarray数组向Python列表的转换
    #ls = a.tolist()
a = np.full((2,3,4),25,dtype=np.int32)
a

array([[[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]],

       [[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]]], dtype=int32)

In [42]:
a.tolist()

[[[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]],
 [[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]]]