In [1]:
#np.gradient(f):计算数组f中元素的梯度，当f为多维时，返回每个维度梯度
    #梯度：连续值之间的变化率，即斜率。(后一个值减去前一个值，再除于后一个值和前一个值之间的距离)

In [2]:
#一维元素的梯度值
import numpy as np
a = np.random.randint(0,20,(5))
a

array([12, 13, 15, 15, 18])

In [5]:
np.gradient(a)  #存在两侧值：1.5=(15-12)/2     #只有一侧值：1=(13-12)/1    3=(18-15)/2 没有的值用本身代替

array([ 1. ,  1.5,  1. ,  1.5,  3. ])

In [6]:
#二维元素的梯度值
c = np.random.randint(0,50,(3,5))
c

array([[29, 30,  4, 31, 36],
       [30,  0, 29, 12, 28],
       [ 4, 11, 39, 10, 21]])

In [7]:
np.gradient(c)   #包括最外层维度的梯度和第二层维度的梯度

[array([[  1. , -30. ,  25. , -19. ,  -8. ],
        [-12.5,  -9.5,  17.5, -10.5,  -7.5],
        [-26. ,  11. ,  10. ,  -2. ,  -7. ]]),
 array([[  1. , -12.5,   0.5,  16. ,   5. ],
        [-30. ,  -0.5,   6. ,  -0.5,  16. ],
        [  7. ,  17.5,  -0.5,  -9. ,  11. ]])]