In [1]:
#NumPy的随机数函数子库：random子库
#np.random的随机数函数(1)
    #rand(d0,d1,..,dn):根据d0-dn创建随机数数组，浮点数，[0,1),均匀分布
    #randn(d0,d1,..,dn):根据d0-dn创建随机数数组，标准正态分布
    #randint(low[,high,shape]):根据shape创建随机整数或整数数组，范围是[low,high)  []表示可选参数
    #seed(s):随机数种子，s是给定的种子值

In [2]:
#rand(d0,d1,..,dn)
import numpy as np
a = np.random.rand(3,4,5)
a

array([[[ 0.7095564 ,  0.68828936,  0.07717903,  0.83334312,  0.08278339],
        [ 0.67111089,  0.99963308,  0.35421238,  0.7632275 ,  0.32282705],
        [ 0.8409011 ,  0.8933431 ,  0.56595069,  0.3928342 ,  0.22256099],
        [ 0.13655454,  0.31322815,  0.01323364,  0.81378172,  0.03123513]],

       [[ 0.02295479,  0.656884  ,  0.036739  ,  0.52123852,  0.80873623],
        [ 0.23433179,  0.13155007,  0.62978164,  0.36780168,  0.57782344],
        [ 0.98743914,  0.68840755,  0.22196819,  0.3729051 ,  0.36476898],
        [ 0.11453921,  0.05836767,  0.01053737,  0.97388979,  0.90589512]],

       [[ 0.06456625,  0.54697261,  0.95149393,  0.16853441,  0.67410696],
        [ 0.30604587,  0.0449015 ,  0.62909933,  0.09001089,  0.88208467],
        [ 0.40597479,  0.6684756 ,  0.04106313,  0.80870168,  0.49033603],
        [ 0.44556783,  0.21884963,  0.51058919,  0.36252017,  0.54176394]]])

In [3]:
#randn(d0,d1,..,dn)
sn = np.random.randn(3,4,5)
sn

array([[[-1.2213204 ,  1.37369615,  0.26162064,  0.67339664,  0.26659278],
        [ 0.02382832,  0.56765836, -0.23247507,  1.19931258,  0.15241177],
        [-0.19414127,  0.525495  , -1.55290637, -1.25061909,  0.0316099 ],
        [-1.29680415,  1.75997987, -0.90593625,  1.10661419,  0.92165929]],

       [[ 0.81816944, -0.60774529, -0.60393586, -0.82312014,  0.20748858],
        [ 0.43121114,  0.40758193, -1.32685119, -0.58773654,  1.1743011 ],
        [-1.04335257, -1.24350643, -0.63625735, -0.53569448,  1.2281313 ],
        [-1.00653296, -0.23058717,  0.33246312,  0.26555261,  0.46437118]],

       [[-1.45986829,  1.54776878,  0.61239592, -2.02391892, -0.40306553],
        [ 0.44633778,  0.24331479, -0.75037215,  1.20127787,  0.02521149],
        [-0.649457  , -0.08432177, -0.26272633,  0.52449694, -0.15790445],
        [ 1.09273681,  0.27068658,  1.62730813, -0.50001495, -0.42685561]]])

In [4]:
#randint(low[,high,shape])
b = np.random.randint(100,200,(3,4))
b

array([[183, 186, 192, 137],
       [191, 100, 138, 152],
       [165, 123, 135, 186]])

In [5]:
#seed(s)
np.random.seed(10)
np.random.randint(100,200,(3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [8]:
np.random.seed(10)
np.random.randint(100,200,(3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [15]:
np.random.randint(100)

72

In [16]:
#np.random的随机数函数(2)
    #shuffle(a):根据数组a的第0轴进行随机排列，改变数组x
    #permutation(a):根据数组a的第0轴产生一个新的乱序数组，不改变数组x
    #choice(a[,size,replace,p]):从一维数组a中以概率p抽取元素，形成size形状新数组，replace表示是否可以重用元素，默认为True 

In [17]:
#shuffle(a)
a = np.random.randint(100,200,(3,4))
a

array([[178, 149, 151, 154],
       [177, 169, 113, 125],
       [113, 192, 186, 130]])

In [19]:
np.random.shuffle(a)
a

array([[113, 192, 186, 130],
       [177, 169, 113, 125],
       [178, 149, 151, 154]])

In [21]:
#permutation(a)
a = np.random.randint(100,200,(3,4))
a

array([[127, 118, 193, 177],
       [122, 123, 194, 111],
       [128, 174, 188, 109]])

In [22]:
np.random.permutation(a)

array([[122, 123, 194, 111],
       [127, 118, 193, 177],
       [128, 174, 188, 109]])

In [23]:
a

array([[127, 118, 193, 177],
       [122, 123, 194, 111],
       [128, 174, 188, 109]])

In [24]:
#choice(a[,size,replace,p])
b = np.random.randint(100,200,(8,))
b

array([171, 188, 111, 117, 146, 107, 175, 128])

In [25]:
np.random.choice(b,(3,2))

array([[188, 146],
       [111, 171],
       [171, 146]])

In [26]:
np.random.choice(b,(3,2),replace=False)

array([[188, 117],
       [175, 111],
       [128, 171]])

In [29]:
np.random.choice(b,(3,2),p=b/np.sum(b))

array([[188, 146],
       [128, 146],
       [146, 171]])

In [30]:
#np.random的随机函数(3)
    #uniform(low,high,size):产生具有均匀分布的数组，low起始值，high结束值，size形状
    #normal(loc,scale,size):产生具有正态分布的数组，loc均值，scale标准差，size形状
    #poisson(lam,size):产生具有泊松分布的数组，lam随机事件发生率，size形状

In [32]:
#uniform(low,high,size)
u = np.random.uniform(0,10,(3,4))
u

array([[ 7.63240587,  8.78096643,  4.17509144,  6.05577564],
       [ 5.13466627,  5.97836648,  2.62215661,  3.00871309],
       [ 0.25399782,  3.03062561,  2.42075875,  5.57578189]])

In [33]:
#normal(loc,scale,size)
n = np.random.normal(10,5,(3,4))
n

array([[  5.02479487,  23.10576259,   8.29556788,   9.18952922],
       [ 12.16479754,   9.97753271,   0.67639306,   6.96137071],
       [ 23.09562592,  13.31796477,  17.45806917,   9.06177508]])