In [ ]:
#NumPy：一个开源的Python科学计算基础库，是SciPy、Pandas等数据处理或科学计算库的基础
    #一个强大的N维数组对象 ndarray
    #广播功能函数，在数组之间进行计算
    #整个C/C++/Fortran代码的工具
    #线性代数、傅里叶变换、随机数生成等功能

In [3]:
#Python有了列表，为啥还要引入N维数组对象(ndarray)
#例：计算A**2+B**3,其中，A和B都是一维数组
def pySum():
    a = [0,1,2,3,4]
    b = [9,8,7,6,5]
    c = []
    for i in range(len(a)):
        c.append(a[i]**2 + b[i]**3)
    return c

print(pySum())

[729, 513, 347, 225, 141]


In [4]:
import numpy as np
def npSum():
    a = np.array([0,1,2,3,4]) #ndarray在程序中的别名是：array
    b = np.array([9,8,7,6,5])
    #ndarray可以去掉元素间运算所需的循环，使一维向量更像单个数据
    #ndarray是用c语言实现的，运算速度较快
    c = a**2 + b**3
    return c

print(npSum())

[729 513 347 225 141]


In [5]:
#ndarray:一个N维数组对象，由两部分构成：
    #实际的数据
    #描述这些数据的元数据（数据维度、数据类型等）

In [6]:
a = np.array([[0,1,2,3,4],[9,8,7,6,5]])
a

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [7]:
type(a)

numpy.ndarray

In [8]:
#np.array()输出成[]形式，元素由空格分割
print(a)

[[0 1 2 3 4]
 [9 8 7 6 5]]


In [10]:
#ndarray对象的属性

In [11]:
#1.ndim：秩，即轴的数量或维度的数量
a.ndim

2

In [12]:
#2.shape：ndarray对象的尺度，对于矩阵，n行m列
a.shape

(2, 5)

In [13]:
#3.size：ndarray对象元素的个数，相当于.shape中n*m的值
a.size

10

In [14]:
#4.dtype：ndarray对象的元素类型
a.dtype

dtype('int64')

In [15]:
#5.itemsize：ndarray对象中每个元素的大小，以字节为单位
a.itemsize

8